theme: jekyll-theme-minimal
title: "Vs. Fheo"
description: "Vs. Fheo is a mod for Friday Night Funkin', including a full engine rework, replays, and more."
show_downloads: true
replace_index_with: "https://cors-thing.puyo.workers.dev/master/"
logo: "https://github.com/KadeDev/Kade-Engine/raw/master/KadeEngineLogo.png"
url: "https://KadeDev.github.io/Kade-Engine/"
